import Foundation

/// The owner's prompt in a user-role text, or nil when the text is the agent's own (P155).
///
/// Agents write machine text as user messages and fire UserPromptSubmit for some of it: Claude's background-task
/// notifications (`<task-notification>…`), slash-command wrappers, local-command output and caveats, bash-mode
/// blocks, interrupt markers, compaction summaries, skill bodies and hook feedback; Codex's contextual fragments
/// (`<environment_context>`, `<turn_aborted>`, `<user_shell_command>`, `<subagent_notification>`, …) and the reply
/// envelope of an async question (`<send_user_message_question_reply>`). Every writer and reader of a row's prompt
/// runs its text through `human`, so none of that is ever shown as what the owner asked.
public enum PromptText {
    /// Wrappers whose text is never the owner's, whatever follows them. A text that opens with any other `<tag>` whose
    /// name holds `-` or `_` and that closes it is taken for a wrapper too (`isGenericWrapper`), so a new one of either
    /// agent's is caught without a list change; an HTML element (`<div>`) never is.
    static let wrappers: [String] = [
        // Claude Code
        "task-notification", "local-command-stdout", "local-command-stderr", "local-command-caveat", "bash-input",
        "bash-stdout", "bash-stderr", "teammate-message", "channel", "user-prompt-submit-hook", "command-message",
        "system-reminder",
        // Codex
        "environment_context", "turn_aborted", "user_shell_command", "subagent_notification", "user_instructions",
        "skill", "hook_prompt", "agent_message_board_notification", "codex_internal_context", "goal_context",
        "current_time_reminder", "image_resize_notice", "user_verification_notice", "send_user_message_question_reply",
        "recommended_plugins", "permissions instructions", "collaboration_mode", "skills_instructions",
        // codex-rs's other contextual fragments (`protocol.rs` `*_OPEN_TAG`, `realtime_context.rs`)
        "environments_instructions", "apps_instructions", "plugins_instructions", "multi_agent_mode", "realtime_conversation",
        "context_window", "context_window_guidance", "startup_context",
        // The Codex app's own (ChatGPT.app 26.928): whole messages it sends for itself. Its context blocks are
        // `appBlocks`, never wrappers: a prompt that opens with one of those tags is the owner's (P663).
        "codex_delegation", "realtime_delegation", "startup_tool_prewarm", "external_event",
    ]

    /// Blocks the Codex app puts inside a message the owner did write (P661): removed where they are closed, with their
    /// attributes (`<in-app-browser-context source="ambient-ui-state">`).
    static let appBlocks: [String] = ["in-app-browser-context", "response-annotations", "page-comment-context", "app-context"]

    /// Blocks removed from a prompt wherever they are closed: Claude's two, then the Codex app's.
    static let inlineBlocks: [String] = ["system-reminder", "user-prompt-submit-hook"] + appBlocks

    /// The app's blocks a preview can cut short, each with what the app always writes at its start: a text that opens
    /// with one of them unclosed and signed so is the app's own, cut (upstream's reducer keeps a prompt's first 110
    /// characters). Anywhere else, or unsigned, an unclosed tag is what the owner typed (P663).
    static let cutBlocks: [(name: String, signatures: [String])] = [
        ("in-app-browser-context", [#"source="ambient-ui-state""#, "This block is automatically supplied"]),
        ("codex_multi_user_message", ["<account_user_id>"]),
    ]

    /// Openings of machine text that has no wrapper.
    static let prefixes: [String] = [
        // Claude Code (only its own caveat sentence: a typed "Caveat: …" is the owner's)
        "Caveat: The messages below were generated by the user while running local commands", "[Request interrupted by user",
        "This session is being continued from a previous conversation", "Stop hook feedback:", "Base directory for this skill:",
        // Codex; its approvals reviewer's prompt ("The following is the Codex agent history whose request action you are
        // assessing", "… added since your last approval assessment"), in a thread that is never a row (P212)
        "Another language model started to solve this problem", "# AGENTS.md instructions", "# Files mentioned by the user:",
        "# Chrome tabs:", "## Referenced chats with Codex:", "The following is the Codex agent history",
        // The Codex app's context headings, which come before its request marker: a text that opens with one and has no
        // marker is a preview cut before the owner's words
        "# Context from my IDE setup:", "# Worktree instructions:", "# Response annotations:", "# Suggested artifact action target:",
        "# Open LaTeX document", "# Files pasted by the user:", "# Applications mentioned by the user:",
        "## Prior conversation with Codex:", "## Referenced ChatGPT conversation:", "# Pull request repair instructions:",
        "# Diff comments:", "# Browser comments:", "# Selected text:", "# Failing PR checks:", "# Pull request merge conflict:",
        "# MCP app context:", "# In app browser:", "# Codex desktop context",
        // OpenCode's synthetic parts of the owner's message (`session/prompt.ts`, `compaction.ts`), which its plugin sends
        // as prompts too
        "Called the Read tool with the following input:", "The following tool was executed by the user",
        "Use the above message and context to generate a prompt and call the task tool with subagent:",
        "Summarize the task tool output above and continue with your task.",
        "Continue if you have next steps, or stop and ask for clarification", "Reading MCP resource:",
    ]

    /// Codex's request marker: the IDE extension and the Codex app put their context first and what the owner typed after
    /// the last marker (`# Context from my IDE setup:` … `## My request for Codex:`; the app's `<in-app-browser-context>`
    /// … `## My request:`). The app reads its own messages back the same way (`/## My request(?: for Codex)?:/g`, the
    /// text after the last). The bare marker is the app's only after the app's context (`opensWithAppContext`, P663).
    static let codexRequestMarker = #"## My request(?: for Codex)?:"#
    static let bareRequestMarker = "## My request:"

    /// A shared thread's sender line (the app's `xr`), as the app matches it.
    static let senderLine = #"^\s*\[from: [^\]\r\n]+\](?:\r?\n|$)"#

    /// The owner's words in `text`, trimmed; "Image" for a prompt that was only images; nil for machine text.
    public static func human(_ text: String?) -> String? {
        guard var text else { return nil }
        if let start = afterRequestMarker(in: text) {
            text = String(text[start...])
        }
        // A shared thread's member wrote these words; the app escaped any tag in them, so none is machine text (P664).
        if let body = sharedBody(in: text) {
            let words = body.trimmingCharacters(in: .whitespacesAndNewlines)
            return words.isEmpty ? nil : words
        }
        if text.contains("[from: "), let from = text.range(of: senderLine, options: .regularExpression) {
            text.removeSubrange(from)
        }
        let hadImages = text.range(of: #"\[Image #\d+\]"#, options: .regularExpression) != nil
        text = removingBlocks(of: inlineBlocks, in: text)
        if opensWithCutAppBlock(text) { return nil }
        text = removingPastes(in: text)
        // A run of placeholders and the spaces around it leave one space.
        text = text.replacingOccurrences(of: #"(?:[ \t]*\[Image #\d+\])+[ \t]*"#, with: " ", options: .regularExpression)
        var trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if let command = slashCommand(in: trimmed) { return command }
        guard !trimmed.isEmpty else { return hadImages ? "Image" : nil }
        if prefixes.contains(where: trimmed.hasPrefix) { return nil }
        if opensWithWrapper(trimmed) || isOpenCodeReadOutput(trimmed) { return nil }
        trimmed = trimmed.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }

    /// Whether a user-role text is the owner's prompt.
    public static func isHuman(_ text: String?) -> Bool { human(text) != nil }

    /// Text that is a JSON value (an object or an array), or the start of an object cut short: machine output, never a
    /// title or a status line (Codex's reviewer answers `{"risk_level":"low","user_authorization":…,"outcome":"allow",…}`,
    /// P212).
    public static func isJSON(_ text: String?) -> Bool {
        guard let trimmed = text?.trimmingCharacters(in: .whitespacesAndNewlines), let first = trimmed.first,
              first == "{" || first == "[" else { return false }
        if (try? JSONSerialization.jsonObject(with: Data(trimmed.utf8))) != nil { return true }
        return trimmed.range(of: #"^\[?\s*\{\s*"[^"\n]{1,64}"\s*:"#, options: .regularExpression) != nil
    }

    /// A Codex review's answer (`ReviewOutputEvent`: `{"findings":[…],"overall_correctness":…,"overall_explanation":…}`),
    /// the last message of a review that is a row of its own (P217), in its own words: its explanation. nil for any
    /// other text.
    public static func reviewExplanation(_ text: String?) -> String? {
        guard isJSON(text), let text, let object = try? JSONSerialization.jsonObject(with: Data(text.utf8)) as? [String: Any],
              object["findings"] != nil,
              let explanation = (object["overall_explanation"] as? String)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !explanation.isEmpty else { return nil }
        return explanation
    }

    /// `<command-name>/x</command-name>` (with `<command-args>`) as the owner typed it: `/x args`.
    static func slashCommand(in text: String) -> String? {
        guard let name = element("command-name", in: text)?.trimmingCharacters(in: .whitespacesAndNewlines),
              !name.isEmpty else { return nil }
        let command = name.hasPrefix("/") ? name : "/" + name
        let args = element("command-args", in: text)?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return args.isEmpty ? command : command + " " + args
    }

    /// The text between `<name>` and `</name>`, the first such element.
    static func element(_ name: String, in text: String) -> String? {
        guard let open = text.range(of: "<\(name)>"),
              let close = text.range(of: "</\(name)>", range: open.upperBound..<text.endIndex) else { return nil }
        return String(text[open.upperBound..<close.lowerBound])
    }

    /// `text` without every closed `<name …>…</name>` block of `names`, attributes and all. An unclosed one stays: the
    /// owner quoting a tag is the owner's (P663); the app's own cut short is `opensWithCutAppBlock`'s.
    static func removingBlocks(of names: [String], in text: String) -> String {
        guard text.contains("<") else { return text }
        var result = text
        for name in names where result.contains("<\(name)") {
            let escaped = NSRegularExpression.escapedPattern(for: name)
            let open = "<" + escaped + #"(?:\s[^>]*)?>"#
            result = result.replacingOccurrences(of: open + #"[\s\S]*?</"# + escaped + #"\s*>"#, with: "", options: .regularExpression)
        }
        return result
    }

    /// Whether `text` opens with one of the app's `cutBlocks`, unclosed, with the app's signature in its tag or right
    /// after it: the app's context cut short, never the owner's words.
    static func opensWithCutAppBlock(_ text: String) -> Bool {
        let trimmed = text.drop { $0.isWhitespace }
        guard trimmed.first == "<" else { return false }
        for (name, signatures) in cutBlocks where trimmed.hasPrefix("<" + name) {
            let after = trimmed.dropFirst(name.count + 1)
            guard after.first == ">" || after.first?.isWhitespace == true, !trimmed.contains("</" + name),
                  let tagEnd = after.firstIndex(of: ">") else { continue }
            let tag = trimmed[..<tagEnd], rest = after[after.index(after: tagEnd)...].drop { $0.isWhitespace }
            if signatures.contains(where: { tag.contains($0) || rest.hasPrefix($0) }) { return true }
        }
        return false
    }

    private static let requestMarker = try? NSRegularExpression(pattern: codexRequestMarker)

    /// Where the owner's words start: after the last request marker; nil for a text with none, and for one whose last
    /// marker is the bare `## My request:` with no app context before it (a prompt that only names the marker, P663).
    static func afterRequestMarker(in text: String) -> String.Index? {
        guard text.contains("## My request"), let marker = requestMarker,
              let last = marker.matches(in: text, range: NSRange(text.startIndex..., in: text)).last,
              let range = Range(last.range, in: text) else { return nil }
        if text[range] == bareRequestMarker, !opensWithAppContext(text[..<range.lowerBound]) { return nil }
        return range.upperBound
    }

    /// Whether the text before a bare marker is the app's context (`bE`): after a shared thread's `[from: …]` line, it
    /// opens with one of the app's headings (`prefixes`), one of its blocks, or JSON (the context a ChatGPT chat sends).
    static func opensWithAppContext(_ before: Substring) -> Bool {
        var head = String(before)
        if head.contains("[from: "), let from = head.range(of: senderLine, options: .regularExpression) { head.removeSubrange(from) }
        head = head.trimmingCharacters(in: .whitespacesAndNewlines)
        return prefixes.contains(where: head.hasPrefix) || appBlocks.contains { head.hasPrefix("<" + $0) } || isJSON(head)
    }

    /// A shared thread's message as the app's reader (`xoe`) takes it: the whole text (after the marker) is one closed
    /// `<codex_multi_user_message>` with a sender id and a `<body>`; its body, unescaped. nil for any other text: a
    /// wrapper typed or quoted in a sentence is the owner's (P664).
    static func sharedBody(in text: String) -> String? {
        let open = "<codex_multi_user_message>", close = "</codex_multi_user_message>"
        guard text.contains(open) else { return nil }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.hasPrefix(open), trimmed.hasSuffix(close), trimmed.count > open.count + close.count,
              trimmed.range(of: open, options: .backwards)?.lowerBound == trimmed.startIndex else { return nil }
        let inner = String(trimmed.dropFirst(open.count).dropLast(close.count))
        guard let sender = element("account_user_id", in: inner), !sender.isEmpty, let body = element("body", in: inner) else { return nil }
        return unescaped(body)
    }

    /// The Codex app's XML escapes, undone as it undoes them.
    static func unescaped(_ text: String) -> String {
        text.replacingOccurrences(of: "&lt;", with: "<").replacingOccurrences(of: "&gt;", with: ">")
            .replacingOccurrences(of: "&quot;", with: "\"").replacingOccurrences(of: "&apos;", with: "'")
            .replacingOccurrences(of: "&amp;", with: "&")
    }

    /// Claude's paste markers (`<pasted_content id="…">` and `</pasted_content id="…">` lines, hooks docs): what the owner
    /// typed around them, else the pasted text itself. A preview cut inside a paste loses its opening marker and the
    /// cut end of a closing one.
    static func removingPastes(in text: String) -> String {
        let open = #"<pasted_content(?:\s[^>]*)?>"#
        let close = #"</pasted_content(?:\s[^>]*)?>"#
        guard text.range(of: "<pasted_content") != nil || text.range(of: "</pasted_content") != nil else { return text }
        var result = text
        var pasted: [String] = []
        while let start = result.range(of: open, options: .regularExpression) {
            if let end = result.range(of: close, options: .regularExpression, range: start.upperBound..<result.endIndex) {
                pasted.append(String(result[start.upperBound..<end.lowerBound]))
                result.removeSubrange(start.lowerBound..<end.upperBound)
            } else {
                result.removeSubrange(start)
            }
        }
        result = result.replacingOccurrences(of: close, with: "", options: .regularExpression)
        result = result.replacingOccurrences(of: #"</?pasted_[^>]*$"#, with: "", options: .regularExpression)
        guard result.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return result }
        let whole = pasted.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
        return whole.isEmpty && !pasted.isEmpty ? "Pasted text" : whole
    }

    /// OpenCode's Read output for an @-mentioned file (`tool/read.ts`): `<path>…</path>` then `<type>…`.
    static func isOpenCodeReadOutput(_ text: String) -> Bool {
        text.hasPrefix("<path>") && text.contains("</path>") && text.contains("<type>")
    }

    static func opensWithWrapper(_ text: String) -> Bool {
        guard text.hasPrefix("<") else { return false }
        for name in wrappers where text.hasPrefix("<\(name)>") || text.hasPrefix("<\(name) ") { return true }
        return isGenericWrapper(text)
    }

    /// `<name …>` whose name has a `-` or `_`, and the text ends with `</name>`: a machine wrapper, never an HTML
    /// element, and never a typed prompt that opens with a custom element (`<my-button>…</my-button> fix it`); Codex's
    /// own matchers require the end marker too. Known wrappers whose text goes on after the close
    /// (`<task-notification>`) are in `wrappers`.
    static func isGenericWrapper(_ text: String) -> Bool {
        let body = text.dropFirst()
        let name = body.prefix { $0.isLetter || $0.isNumber || $0 == "-" || $0 == "_" }
        guard !name.isEmpty, name.contains(where: { $0 == "-" || $0 == "_" }), name.first?.isLetter == true else { return false }
        let after = body.dropFirst(name.count).first
        guard after == ">" || after == " " else { return false }
        return text.hasSuffix("</\(name)>")
    }
}
