import Foundation
import Testing
@testable import IslandEngine
import OpenIslandCore

/// P155: machine text written as a user message is never the owner's prompt. One case per kind of injected text
/// (Claude Code's and Codex's public formats), and human texts that must pass. Ids and texts are fictional.
struct PromptTextTests {
    @Test(arguments: [
        // Claude Code
        "<task-notification>\n<task-id>b1a2c3d4</task-id>\n<tool-use-id>toolu_01ABC</tool-use-id>\n<status>completed</status>\n<summary>Background command finished</summary>\n</task-notification>\nRead the output file to retrieve the result.",
        "<local-command-stdout>Set model to opus</local-command-stdout>",
        "<local-command-stderr>error</local-command-stderr>",
        "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
        "Caveat: The messages below were generated by the user while running local commands.",
        "<bash-input>ls</bash-input>",
        "<bash-stdout>file</bash-stdout><bash-stderr></bash-stderr>",
        "[Request interrupted by user]",
        "[Request interrupted by user for tool use]",
        "This session is being continued from a previous conversation that ran out of context.",
        "Base directory for this skill: /tmp/skills/example",
        "Stop hook feedback:\nkeep going",
        "<user-prompt-submit-hook>blocked</user-prompt-submit-hook>",
        "<teammate-message teammate_id=\"t1\">done</teammate-message>",
        "<channel source=\"webhook\">payload</channel>",
        "<system-reminder>be brief</system-reminder>",
        // Codex
        "<environment_context><cwd>/tmp/project</cwd></environment_context>",
        "# AGENTS.md instructions for /tmp/project\n<INSTRUCTIONS>…</INSTRUCTIONS>",
        "<turn_aborted>The user interrupted the previous turn on purpose.</turn_aborted>",
        "<user_shell_command><command>ls</command><result>ok</result></user_shell_command>",
        "<subagent_notification>worker finished</subagent_notification>",
        "<user_instructions>be terse</user_instructions>",
        "<skill><name>example</name><path>/tmp/skill</path></skill>",
        "<hook_prompt hook_run_id=\"h1\">continue</hook_prompt>",
        "<agent_message_board_notification>x</agent_message_board_notification>",
        "<goal_context>x</goal_context>",
        "<current_time_reminder>x</current_time_reminder>",
        "Another language model started to solve this problem and produced a summary of its thinking process.",
        "<send_user_message_question_reply>\n[{\"answer\":\"Keep it\",\"question\":\"Remove Figure 3?\",\"questionItemId\":\"[\\\"request_user_input_async\\\",\\\"call_A1\\\",0]\"}]\n</send_user_message_question_reply>",
        "# Context from my IDE setup:\n## Open tabs:\n- a.swift\n## My request for Codex:\n<send_user_message_question_reply>\n[]\n</send_user_message_question_reply>",
        // A future wrapper of either agent: a tag with `-` or `_` that closes.
        "<future_agent_note>x</future_agent_note>",
        "<some-new-wrapper kind=\"a\">x</some-new-wrapper>",
        // Blank
        "   \n\t",
    ])
    func machineTextIsNeverAPrompt(_ text: String) {
        #expect(PromptText.human(text) == nil)
    }

    @Test
    func humanTextsPass() {
        #expect(PromptText.human("fix the failing tests") == "fix the failing tests")
        #expect(PromptText.human("  trim me \n") == "trim me")
        #expect(PromptText.human("<div>keep html</div> as it is") == "<div>keep html</div> as it is")
        #expect(PromptText.human("Caveat emptor: read this first") == "Caveat emptor: read this first")
        #expect(PromptText.human("why does <task-notification> show up in my rows?") == "why does <task-notification> show up in my rows?")
        // An unclosed tag that only looks like a wrapper.
        #expect(PromptText.human("<my_thing is broken") == "<my_thing is broken")
    }

    @Test
    func slashCommandsReadAsTyped() {
        let wrapped = "<command-message>review is running…</command-message>\n<command-name>/review</command-name>\n<command-args>the diff</command-args>"
        #expect(PromptText.human(wrapped) == "/review the diff")
        #expect(PromptText.human("<command-name>/clear</command-name>\n<command-args></command-args>") == "/clear")
    }

    @Test
    func remindersAndImagesAreTakenOut() {
        #expect(PromptText.human("<system-reminder>note</system-reminder>\nrename the file") == "rename the file")
        #expect(PromptText.human("look at this [Image #17] [Image #18] please") == "look at this please")
        #expect(PromptText.human("[Image #1]") == "Image")
        #expect(PromptText.human("[Image #1] [Image #2]") == "Image")
    }

    @Test
    func codexIdeWrapperKeepsTheRequest() {
        #expect(PromptText.human("# Context from my IDE setup:\n## Active file: a.swift\n## My request for Codex:\nadd a test") == "add a test")
    }

    /// Live hooks: a UserPromptSubmit carrying a notification keeps the session's last human prompt.
    @Test
    func metadataKeepsTheLastHumanPrompt() {
        let current = AgentSession(id: "s", title: "Claude · p", tool: .claudeCode, phase: .running, summary: "",
                                   updatedAt: Date(), claudeMetadata: ClaudeSessionMetadata(initialUserPrompt: "first", lastUserPrompt: "fix it"))
        let event = AgentEvent.claudeSessionMetadataUpdated(ClaudeSessionMetadataUpdated(
            sessionID: "s", claudeMetadata: ClaudeSessionMetadata(initialUserPrompt: "first", lastUserPrompt: "<task-notification><task-id>x</task-id></task-notification>"),
            timestamp: Date()))
        guard case let .claudeSessionMetadataUpdated(payload) = PromptText.sanitized(event, current: current) else {
            Issue.record("not a metadata update")
            return
        }
        #expect(payload.claudeMetadata.lastUserPrompt == "fix it")
        #expect(payload.claudeMetadata.initialUserPrompt == "first")

        let codex = AgentEvent.sessionMetadataUpdated(SessionMetadataUpdated(
            sessionID: "s", codexMetadata: CodexSessionMetadata(lastUserPrompt: "<send_user_message_question_reply>[]</send_user_message_question_reply>"),
            timestamp: Date()))
        guard case let .sessionMetadataUpdated(codexPayload) = PromptText.sanitized(codex, current: nil) else {
            Issue.record("not a metadata update")
            return
        }
        #expect(codexPayload.codexMetadata.lastUserPrompt == nil)
    }
}
