import Foundation
import Testing
@testable import IslandEngine
import OpenIslandCore

/// A prompt the owner typed that opens with "Caveat:" is theirs: only Claude Code's own caveat sentence ("Caveat: The
/// messages below were generated by the user while running local commands…") is machine text (P155).
struct PromptTextTypedCaveatTests {
    @Test
    func aTypedCaveatIsTheOwnersPrompt() {
        #expect(PromptText.human("Caveat: this touches prod, go ahead anyway") == "Caveat: this touches prod, go ahead anyway")
        // Claude Code's own caveat stays machine text.
        #expect(PromptText.human("Caveat: The messages below were generated by the user while running local commands. DO NOT respond.") == nil)
    }
}
